name: e2e

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**/example/**"
      - "**/flutterfire_ui/**"
      - "**/cloud_firestore_odm/**"
      - "**.md"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**/example/**"
      - "**/flutterfire_ui/**"
      - "**/cloud_firestore_odm/**"
      - "**.md"

jobs:
  android:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
#      - name: DNSControl preview
#        uses: koenrh/dnscontrol-action@v3
#        with:
#          args: preview
#          config_file: 'dns/dnsconfig.js'
#          creds_file: 'dns/creds.json'
#      - name: DNSControl push
#        uses: koenrh/dnscontrol-action@v3
#        with:
#          args: push
#          config_file: 'dns/dnsconfig.js'
#          creds_file: 'dns/creds.json'
      - uses: actions/setup-node@v2
        name: Install Node.js 16
        with:
          node-version: "16"
      - name: Configure JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: actions/cache@v2
        name: Gradle Cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-v2-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-v2
      - uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd
      - name: Generate AVD snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_atd
          arch: x86
          profile: Galaxy Nexus
          force-avd-creation: false
          emulator-options: -no-snapshot -nojni -memory 2048 -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -timezone 'Europe/London' -cores 2
          disable-animations: false
          channel: canary
          script: echo "Generated AVD snapshot for caching"
      - name: Firebase Emulator Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: firebase-emulators-v2-${{ github.run_id }}
          restore-keys: firebase-emulators-v2
      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
          flutter config --no-enable-web --no-enable-ios --no-enable-macos-desktop
          sudo npm i -g firebase-tools
      - name: "Build Application"
        working-directory: tests
        run: |
          flutter build apk --debug --target=./test_driver/driver_e2e.dart --dart-define=CI=true --no-android-gradle-daemon
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "E2E Tests"
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 40
        with:
          api-level: 30
          arch: x86
          target: google_atd
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          channel: canary
          profile: Galaxy Nexus
          working-directory: tests
          script: |
            sleep 15
            $ANDROID_HOME/platform-tools/adb logcat '*:E' > adb-log.txt &
            flutter drive --target=./test_driver/driver_e2e.dart --dart-define=CI=true

      - name: Compress Emulator Log
        if: always()
        run: cd tests/ && gzip -9 adb-log.txt
        shell: bash

      - name: Upload Emulator Log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.api-level }}-${{ matrix.arch }}-${{matrix.target}}-${{matrix.first-boot-delay}}-${{matrix.iteration}}-adb_logs
          path: tests/adb-log.txt.gz
